### ISSUE TITLE
OPC Publisher configuration for one message per node per 300 ms

### ISSUE THREAD

**Issue by mandar-opc** [Azure/Industrial-IoT#644] opened 2020-07-28 17:01 UTC
Hi Team,

We are trying to get data from OPC Server (Kepserver) on IoT Edge via OPC Publisher module (mcr.microsoft.com/iotedge/opc-publisher:linux-amd64). 
There are some 800 ~ 1000 tags/sensors and they generate data at max once every 300 ms. But we do not know how many of those tags will generate data every 300 ms and hence we don't know how exactly we can batch these messages. Our requirement is that we must get exactly one message per node per 300 ms on OPC Publisher from Kepserver. Can you please guide us what OPC Publisher configuration should we use for this?

Thanks!

**Comment by luiscantero** [comment] 2020-09-07 19:57
@mandar-opc I was told that this is a duplicate of issue #667. I will close this issue and we will get back through 667. Sorry for the long delay.

**Closed by luiscantero** 2020-09-07 19:57 UTC
Labels: Publisher
