### ISSUE TITLE
OpcPublisher: BadSubscriptionIdInvalid after a while

### ISSUE THREAD

**Issue by dcanfyn** [Azure/Industrial-IoT#138] opened 2019-10-21 13:35 UTC
Hi,

We have an OpcPublisher running. It's running fine for days and suddenly it stops sending data for the subscription with the lowest publishing interval (1000ms). This is happening on two different Edge devices, 1 connected to a Siemens OPC UA server and 1 connected to a Kepware server.

**To Reproduce**
1. Install IoT Egde 1.0.9-rc1 on Windows 10 agent PC
2. Push node configuration to the device with 3 different publishing intervals (1000ms, 5000ms and 30000ms) = 3 subscriptions
3. Wait for 1,2,3,... days
4. See error (iotedge logs OpcPublisher --tail 100 -f) --> Subscription with lowest interval loses connection

**Expected behavior**
Publisher keeps subscriptions.

**Log**
{"log":"[07:28:53 ERR] Exception\r\n","stream":"stdout","time":"2019-10-17T07:28:53.8924897Z"}
{"log":"Opc.Ua.ServiceResultException: BadSubscriptionIdInvalid\r\n","stream":"stdout","time":"2019-10-17T07:28:53.8924897Z"}
{"log":"   at Opc.Ua.Client.Subscription.SetPublishingMode(Boolean enabled)\r\n","stream":"stdout","time":"2019-10-17T07:28:53.8924897Z"}
{"log":"   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in C:\\app\\opcpublisher\\OpcSession.cs:line 407\r\n","stream":"stdout","time":"2019-10-17T07:28:53.8924897Z"}
{"log":"[07:29:03 ERR] Exception\r\n","stream":"stdout","time":"2019-10-17T07:29:03.8999995Z"}
{"log":"Opc.Ua.ServiceResultException: BadSubscriptionIdInvalid\r\n","stream":"stdout","time":"2019-10-17T07:29:03.8999995Z"}
{"log":"   at Opc.Ua.Client.Subscription.SetPublishingMode(Boolean enabled)\r\n","stream":"stdout","time":"2019-10-17T07:29:03.8999995Z"}
{"log":"   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in C:\\app\\opcpublisher\\OpcSession.cs:line 407\r\n","stream":"stdout","time":"2019-10-17T07:29:03.8999995Z"}
{"log":"[07:29:13 ERR] Exception\r\n","stream":"stdout","time":"2019-10-17T07:29:13.903782Z"}
{"log":"Opc.Ua.ServiceResultException: BadSubscriptionIdInvalid\r\n","stream":"stdout","time":"2019-10-17T07:29:13.903782Z"}
{"log":"   at Opc.Ua.Client.Subscription.SetPublishingMode(Boolean enabled)\r\n","stream":"stdout","time":"2019-10-17T07:29:13.903782Z"}
{"log":"   at OpcPublisher.OpcSession.MonitorNodesAsync(CancellationToken ct) in C:\\app\\opcpublisher\\OpcSession.cs:line 407\r\n","stream":"stdout","time":"2019-10-17T07:29:13.903782Z"}

****
 - OS: Windows 10 LTSC
 - edgeHub and edgeAgent = 1.0.9-rc1

**Additional context**
We now created 2 seperate edge devices which are monitoring the same OPC server, that way we can find out or the 2 modules are losing the subcription at the same time (OPC UA server is causing the issue) or one module loses the subcription and the other doesn't (OpcPublisher module (or edge) is causing the issue)

**Comment by mregen** [comment] 2019-10-23 07:42
Hi @dcanfyn, double checking: With lowest interval you mean the 30s subscription?

**Comment by pleinolijf** [comment] 2019-10-23 13:15
> 
> 
> Hi @dcanfyn, double checking: With lowest interval you mean the 30s subscription?

No, 1000ms.

**Comment by marcschier** [comment] 2019-10-23 15:28
Apologies, but one more ask - I checked back with the team, and we recently fixed an issue that prevented a "correct" session "reconnect" in some cases.  The version with the fix is 2.5.1.   Is the issue happening on 2.5.1, or would it be possible to update the publisher to 2.5.1 and regress?

**Comment by dcanfyn** [comment] 2019-10-24 07:53
> Apologies, but one more ask - I checked back with the team, and we recently fixed an issue that prevented a "correct" session "reconnect" in some cases. The version with the fix is 2.5.1. Is the issue happening on 2.5.1, or would it be possible to update the publisher to 2.5.1 and regress?

We did change it now and are testing if this solves the problem. Thanks for the response. I'll close this issue if it's fixed.

**Comment by pleinolijf** [comment] 2019-12-10 11:44
> 
> 
> > Apologies, but one more ask - I checked back with the team, and we recently fixed an issue that prevented a "correct" session "reconnect" in some cases. The version with the fix is 2.5.1. Is the issue happening on 2.5.1, or would it be possible to update the publisher to 2.5.1 and regress?
> 
> We did change it now and are testing if this solves the problem. Thanks for the response. I'll close this issue if it's fixed.

v2.5.1 does not fix the problem for us. We are collaborating with Microsoft on this.

**Comment by pleinolijf** [comment] 2019-12-30 21:58
v2.5.2 incorporates code that will automatically renew the subscription upon catching the exception. While this does not fix the cause of the error, it does minimize to the best extent any data loss, so this is an acceptable solution for us and the client.

**Comment by pleinolijf** [comment] 2020-02-10 12:48
Some extra feedback for anyone stumbling upon this issue: v2.5.2 contains another bug causing the module to stop sending any new messages after the keepalive request fails.

This was fixed in **v2.5.3** (not yet officially released at time of writing).  After some weeks on acceptance, we are running that now in production.
Issue may be closed, as far as I am concerned.

**Comment by omarine** [comment] 2020-02-14 12:49
Hello,

do you have an official date for the release of the v2.5.3 ?
![image](https://user-images.githubusercontent.com/13197345/74532976-c9bf3f80-4f30-11ea-8ad8-ca014f7b1947.png)

**Comment by guybartal** [comment] 2020-02-24 05:57
Hi,

I need this fix as well for my customer, can I we have clarity when will it be released?

Meanwhile is there a stable branch with that fix that we can use for a POC?

**Comment by chmagitt** [comment] 2020-03-05 16:42
Hello 

Can you please share the date for 2.5.3 ?

**Comment by marcschier** [comment] 2020-03-10 10:06
2.5.3 fixes this, and has been released several moons ago but we missed tagging it - I just uploaded the tag - you can find the codebase in the release/2.5.3 branch and with "2.5.3" and "2.5" tag on mcr.  We are going to fix the MCR presence soon, so it should show up on dockerhub as well.   This is also been fixed in 2.6* (aka master) even though the code there is completely new.

**Closed by marcschier** 2020-03-10 10:06 UTC
Labels: Publisher, bug
