### ISSUE TITLE
Documentation - Direct calls in opc-twin 

### ISSUE THREAD

**Issue by pesetskyps** [Azure/Industrial-IoT#2011] opened 2023-07-05 17:15 UTC
**I would like to be able to invoke direct calls from my microservice to opc-publisher triggering browsing processing and getting the value on the demand from the opc node.**
Is there ability to guide to the docs and the code I can dig into to understand how and with what parameters I should invoke direct call from my microservice to get value on demand from opc-ua node and also trigger browsing process.

**Comment by marcschier** [comment] 2023-07-06 05:01
Please find docs here: https://github.com/Azure/Industrial-IoT/tree/main/docs/opc-publisher#programming-against-opc-publisher-using-the-opc-publisher-api.  A sample setup is in deploy/docker folder.

**Comment by marcschier** [comment] 2023-07-06 11:21
Duplicate of #1971 - building samples for OPC Publisher APIs

**Closed as completed by marcschier** 2023-07-06 11:21 UTC
