### ISSUE TITLE
Endpoint Activation: Never goes to ActivatedAndConnect and Ready State

### ISSUE THREAD

**Issue by msha1026** [Azure/Industrial-IoT#297] opened 2020-03-06 01:41 UTC
**Describe the bug**
When activating an endpoint through Postman, the `activationState` never changes to `ActivatedAndConnected` and `endpointState` does not change to `Ready`.
![image](https://user-images.githubusercontent.com/15195985/76041599-68730680-5f07-11ea-959a-c0f85d146a3b.png)

**To Reproduce**
1. Deploy 2.6 IIoT Stack Version
2. Follow tutorial to get setup on postman
3. Activate an endpoint
4. activationState never changes out of Activated

**Expected behavior**
Expect to see `activationState` and `endpointState` to look like the following after a minute or less:
![image](https://user-images.githubusercontent.com/15195985/76041765-d28bab80-5f07-11ea-9735-c784fbe25489.png)

**Screenshots**
Here are logs pulled from the opctwin module too when trying to activate an endpoint:
![image](https://user-images.githubusercontent.com/15195985/76041985-6eb5b280-5f08-11ea-948f-ca8c260c217e.png)

**Comment by cristipogacean** [comment] 2020-03-06 07:57
Do you use a secure endpoint when connecting to the server? if so, probably the server needs to be configured to trust the twin's certificate  requires the twin's certificate. Can you check if the server has an endpoint with security policy none and try that out?

**Comment by msha1026** [comment] 2020-03-06 15:42
I have already trusted the twin’s certificate on the server.

**Comment by marcschier** [comment] 2020-03-06 17:42
It looks like connection to iot hub (appears you run outside of iot edge) is failing Everytime the module is trying to report the connection ready state.  Possible that there are 2 twin modules connecting to via the same identity?

**Comment by msha1026** [comment] 2020-03-06 18:09
Hm interesting @marcschier . Is there a way to check this? When I do an `iotedge list`, I only see one instance of the twin module.

**Comment by msha1026** [comment] 2020-03-06 19:21
When restarting the twin module, activation/deactivation works once, but then does not work again without having to restart the twin module again.

**Comment by marcschier** [comment] 2020-03-07 14:44
It would be super helpful to have a step by step repro, e.g. how was the gateway installed?  Os version, edge version, etc.  As the simulated edges do not exhibit this issue it would help to isolate the difference to our simulated edge deployments.

**Comment by msha1026** [comment] 2020-03-08 23:42
Hi Marc, FYI we are using the Linux Gateway that gets deployed with the all in one deployment and using our own PLC container. All edge modules are pulling from the 2.6.1 tag. I can get a full step by step repro to you on Monday.

**Comment by msha1026** [comment] 2020-03-10 22:12
Hi @marcschier , I will be emailing you a full step-by-step repro soon. Please be on the lookout. Thanks!

**Comment by marcschier** [comment] 2020-03-11 11:06
Hi @msha1026 - got it - we will repro.   One bug is that the documentation for postman tutorial is provides a wrong path for the publisher API.  We shall change that to /publisher.  But the activation state and endpoint state is something that we have so far not seen.  To isolate while we reproduce I would like you to also try out against the full simulation instead of creating your own IoT Edge VM, would that be possible?

**Comment by marcschier** [comment] 2020-03-19 15:01
Hi @msha1026 - I just checked in a activation scenario test - tag 2.6.119.  I was able to reproduce race conditions in the twin module and iot hub sdk on "close", between UpdateProperties and CloseAsync which can lead to unresponsiveness of the module.  This is probably triggered somehow by high load on the module for other work, such as browsing.   Without it I can easily get into this state after around 30 activate/browse/deactivate cycles.  With the fixes I ran 1000 cycles on all connected sessions without seeing issues.   Very early, but could you give 2.6.119 a try while I do more testing?

**Comment by msha1026** [comment] 2020-03-19 22:26
Hi @marcschier, after some tests with 2.6.119 modules, we are still seeing the same issues of the endpoint hanging in `Activated` after a deactivate/activate cycle with TKE. We also notice browsing will push it into this hung `Activated` state as well.

**Comment by msha1026** [comment] 2020-03-24 17:27
@marcschier I have spun up another deployment on Friday which uses the 2.6.122 modules. We have not seen the hung Activated state yet which is promising. We will continue testing and let you know if the issue arises again.

**Comment by marcschier** [comment] 2020-03-25 10:20
@msha1026, greatly appreciated.  There is another fix just pushed today where the endpoint state is not updated from disconnected even though the state is != disconnected on the twin.   This happens when you activate, deactivate, activate.

**Comment by marcschier** [comment] 2020-03-29 06:51
We believe this is fixed.  Please reopen if you still see issues.

**Closed by marcschier** 2020-03-29 06:51 UTC
Labels: bug, in progress
