### ISSUE TITLE
arm32v7 not supported on 2.9

### ISSUE THREAD

**Issue by steffenbeermann** [Azure/Industrial-IoT#2196] opened 2024-02-27 07:46 UTC
**Describe the bug**
When deploying OPC Publisher with the newest versions 2.9 and the previews of 2.9.4 to an arm32v7 device (for me raspberry pi) I get the error "exec /usr/bin/dotnet: exec format error"

**To Reproduce**
1. Deploy OPC Publisher to arm32v7 device
2. The logs of OPC Publisher

**Expected behavior**
As I understood the OPC Publisher Images should be multi arch and therefor we should be able to use the tags 2.9 or 2.9.4

**Desktop (please complete the following information):**
 - OS: Debian arm32v7

**Comment by marcschier** [comment] 2024-06-14 07:40
Please could you try with 2.9.8 release and let me know if the issue is fixed?

**Comment by marcschier** [comment] 2024-06-18 09:54
Please reopen if the issue is not fixed in 2.9.8

**Closed as completed by marcschier** 2024-06-18 09:54 UTC
Labels: bug
