### ISSUE TITLE
Telemetry data - OPC publisher version 2.7

### ISSUE THREAD

**Issue by SandeepThombare** [Azure/Industrial-IoT#956] opened 2020-12-05 02:22 UTC
Hi,
I am trying to get "EndpointId" field in "ExtensionFields" of telemetry data using standalone OPC publisher module 2.7. 

I am expecting data model as shown below,
 **{
    "NodeId": "nsu=ThingWorx Industrial Connectivity;s=Sim.PLC.Ramp1",
    "EndpointUrl": "opc.tcp://192.1.4.4:49320/",
    "ApplicationUri": "urn:opcua:PTC.ThingWorxIC.1:UA%20Server",
    "DisplayName": "Ramp1",
    "Timestamp": "2020-12-04T12:36:01.5690773Z",
    "Status": "Good",
    "Value": {
      "Value": 79,
      "SourceTimestamp": "2020-12-04T12:36:01.1250279Z",
      "ServerTimestamp": "2020-12-04T12:36:01.1250279Z"
    },
    "SequenceNumber": 2,
    "ExtensionFields": {
      "EndpointId": "uat96466bafeddbe8faf32a95193a890dd250b8e271",
      "PublisherId": "uat96466bafeddbe8faf32a95193a890dd250b8e271",
      "DataSetWriterId": "uat96466bafeddbe8faf32a95193a890dd250b8e271"
    }
  },**

But I am getting telemetry data as shown below,
**{
    "NodeId": "nsu=ThingWorx Industrial Connectivity;s=Be.KP1KM1_OVERVERHIT",
    "EndpointUrl": "opc.tcp://iot002:49320/",
    "ApplicationUri": "urn:iot002:PTC.ThingWorxIC.1:UA%20Server",
    "DisplayName": "oververhitting [°C]",
    "Timestamp": "2020-10-15T11:56:34.0131379Z",
    "Value": {
      "Value": 14,
      "SourceTimestamp": "2020-10-15T11:56:33.082042Z",
      "ServerTimestamp": "2020-10-15T11:56:33.082042Z"
    },
    "SequenceNumber": 1,
    "ExtensionFields": {
      "PublisherId": "Standalone_test_edge_sim01_publisher",
      "DataSetWriterId": "opc.tcp://iot002:49320_98e40be00c1bacf7b0f1201952e96d3b877e12d6"
    }
  },**

1.Could you please let me how I can enable "EndpointID" field in telemetry?

2.Please help me to understand why there is difference in values of "PublisherId" and "DataSetWriterId". 
  **Example:-** The expected telemetry have "PublisherId": "uat96466bafeddbe8faf32a95193a890ed250b8e184",  "DataSetWriterId": "uat96466bafeddbe8faf32a95193a890ed250b8e184" and current telemetry data have "PublisherId": "Standalone_test_edge_sim01_publisher", "DataSetWriterId":"opc.tcp://iot002:49320_98e40be00c1bacf7b0f1201952e96d3b877e12d6"

Your prompt response would be highly appreciated. 
@monikavar  @cristipogacean

**Comment by barnstee** [comment] 2020-12-08 11:19
Closing as a dupe of https://github.com/Azure/iot-edge-opc-publisher/issues/282

**Closed by barnstee** 2020-12-08 11:19 UTC
Labels: Publisher, documentation
